Email 2step
enonic/app-simple-idprovider pull request #33
Opened 2021-07-20 14:08 UTC by poi33

Added a 2 step authentication. Its possible to turn this off in the userstore settings. by **default** this is turned **on**.

It will send a login code the email of the users that is being used to login.

2021-07-21 08:59 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +            authLib.logout(); // this is super hacky
If anyone has a proper way to check if a user + password is correct without a login. Please do tell. 
Even the "scope: request" above gives a user full login. So we have to log them out again after.

2021-07-21 09:24 UTC, sigdestad commented
A solution might be to implement the authentication directly in the IDprovider (replicate the code currently stored in xp login method). Other, and perhaps better alternative is to expose an "authenticate" method in the xp API in addition to login?

2021-07-21 12:51 UTC, ComLock requested changes

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/login.js
> +        location.href = override || CONFIG.redirectUrl;
Interesting. Guess since this is client side code reassigning globals inside a function is fine.
Javascript passes Objects (including Arrays) as references, which means a function can have unforseen consequences (blackbox). Which is why eslint will warn about param reassign. So lately I'm trying to avoid modifying anything sent into a function, but rather apply changes to a local copy JSON.parse(JSON.stringify(passedInObject)), and return the modified local copy. When you are calling a function (maybe from some lib you don't own) and want to make sure nothing you pass in is modified, you could JSON.parse(JSON.stringify()) on any object before passing it to the function, hehehehe

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/login.js
> +        action: "login",
Why are you changing single quotes to double quotes? This is not json...

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/login.js
> +        password: $("#inputPassword").val(),
eslint would typically complain about this being useless comma

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    enableFormSubmit(false);
Where does enableFormSubmit come from???

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    const code = $("#inputCode");
This const is only used one time, I typically avoid that.

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    const storrageData = window.sessionStorage;
sessionStorage is a global, why do we need a const referring to it, can't we just use sessionStorage directly, or window.sessionStorage so it's clear this is browser code.

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    const data = {
Another const only used once, unless you are debugging, this could be put directly inside the JSON.stringify below?

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    const body = getLoginPage();
I prefer defining functions before I use them. Trusting hoisting can be risky... https://www.jenniferbland.com/how-hoisting-in-javascript-can-cause-unexpected-results/

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    else if (action == 'reset' && params.token) {
I (and eslint I believe) prefer triple equals
https://www.w3schools.com/js/js_comparisons.asp

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    const params = req.params;
Might aswell const token = req.params.token; Since that's the only thing used below?

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    const params = req.params;
Guess you haven't setup a transpiler that supports deconstruction. Or this would look nicer
const {action, token} = req.params;

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    } else if (action == 'code') {
Hmm, everytime action is 'login', but user or password is missing the other 3 if's has to be executed before the "fallback" is returned. Perhaps a switch on action, and the if(user&&password) inside the cases?

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    let codeRedirect;
could use ternary

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    return contextLib.runAsAdmin(function () {
Guess there isn't setup a transpiler that supports fat arrow.

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +        idProviderConfig.emailCode == undefined
This is an example where triple equals actually matter: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#strict_equality_and_undefined

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +            authLib.logout(); // this is super hacky
How about a localhost http-client login? HEHEHE ROFL

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +            authLib.logout(); // this is super hacky
Perhaps discuss this with @alansemenov, @rymsha or @sigdestad

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +            user: user,
Guess you don't have a transpiler which supports Object Property Value Shorthand

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/idprovider/idprovider.js
> +    else {
else not needed because of return in if.

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/mail.js
> +    const result = mailLib.send({
Unused const? eslint would normally complain about this.

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/render/render.js
> +        codeUrl,
Does Enonic XP support Object Property Value Shorthand? Since you didn't use it elsewhere...

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/render/render.js
> +    const redirectUrl = portalLib.logoutUrl();
So many const only used once

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/render/render.js
> +    const stylePath = "themes/" + theme.split('-', 1)[0] + "-theme.css";
No transpiler supporting string literals? ``

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/resetToken.js
> +    const bean = __.newBean('com.enonic.app.simpleidprovider.TokenGeneratorService');
Hmm, I guess this another question for @alansemenov, @rymsha or @sigdestad should beans be "instansiated" once for entire js file, and used inside multiple functions, rather than beeing "instansiated" on every call of a function?

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/twoStepToken.js
> +                p.twoStepTimestamp = Date.now();
valuelib for indexing as date time, not just stringified date?

2021-07-21 12:51 UTC, ComLock commented on src/main/resources/lib/twoStepToken.js
> +    var bean = __.newBean(
Same question as before. Should beans be "instansiated" all over the place?

2021-07-21 13:08 UTC, poi33 commented on src/main/resources/assets/js/login.js
> +        location.href = override || CONFIG.redirectUrl;
I'm also not a big fan of modfying sent in parameters. Its difficult to understand and follow when things change. 
I not a fan of `JSON.parse( JSON.stringy ())` its really slow, but we don't have `structuredClone` yet, and hopefully one day it will be supported.
I'll ersolve this issue since, it originally concerns modifying a global window variable?

2021-07-21 13:17 UTC, ComLock commented on src/main/resources/assets/js/login.js
> +        location.href = override || CONFIG.redirectUrl;
Yeah, just a comment

2021-07-21 13:19 UTC, poi33 commented on src/main/resources/assets/js/login.js
> +        action: "login",
Don't want to mix single and double quotes on string initialization. So i try to change them to be double quotes so its the same in the entire project.

2021-07-21 13:20 UTC, poi33 commented on src/main/resources/assets/js/login.js
> +        password: $("#inputPassword").val(),
I'm a big fan of trailing commas. Want me to remove it?

2021-07-21 13:24 UTC, poi33 commented on src/main/resources/assets/js/send-code.js
> +    enableFormSubmit(false);
Yes this is super confusing. This project: [link](https://github.com/enonic/lib-idprovider-display/), this [file](https://github.com/enonic/lib-idprovider-display/blob/9d4a74b83505b2484c8269bbdbf825e20c8076a2/src/main/resources/lib/display/page.html#L126). 
I don't know why the seperated the view in a different project, but its only confusing with the javascript that is included. Want to create an issue about it? I'm not a fan of the seperated view rendering. Maybe we can create a good view lib that all our idproviders use?

2021-07-21 13:27 UTC, poi33 commented on src/main/resources/assets/js/send-code.js
> +    const code = $("#inputCode");
Yeah in this case i agree. Not a fan of fetching and assigning in a single line of code, but this is really short.

2021-07-21 13:30 UTC, poi33 commented on src/main/resources/assets/js/send-code.js
> +    const storrageData = window.sessionStorage;
yeah since its only used twice i'll change it. 
If you have to write some.really.long.path.to.some.value then i would prefer a variable so easier to understand the code.

2021-07-21 13:35 UTC, ComLock commented on src/main/resources/assets/js/login.js
> +        action: "login",
In perl it actually makes a difference. Single quoted strings are not interpolated. Thus they are more efficient. Which is probably why I prefer single quotes. :)

2021-07-21 13:37 UTC, poi33 commented on src/main/resources/assets/js/send-code.js
> +    const data = {
The code block and handles the ajax would not be possible to seperate from the code block and handles the object assigment. Yes, you can write it together, but its becomes difficult to read. I try to seperate them so i don't confuse the ajax method with the object assigment.
Do you never add a variable for readability? Never seperate your code unless its functional?
Why no issue on the success or error param? That is function assigment done when you could move it inside the ajax call?

2021-07-21 13:37 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    enableFormSubmit(false);
Regardless of where it comes from, it's not imported/required, so appears to be some kinda global? Seems very hacky to me...

2021-07-21 13:39 UTC, ComLock commented on src/main/resources/assets/js/send-code.js
> +    const data = {
Sometimes, just a comment.

2021-07-21 13:40 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    const body = getLoginPage();
Yeah i usually just follow what was done previusly. I'll change it, i don't want some obscure hoisting issue.

2021-07-21 13:52 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    else if (action == 'reset' && params.token) {
I find w3schools to be bad code and teaching for anyone beyond beginner level.
You mean the default eslint config? Since everyone sets up own linting and linting is personal opinion? 
Does not everyone just use `===` because they don't want and issues? I do get confused by it when comparing objects and don't fully understand it then. 
You want me to change it because its common practice by others? I don't mind 42 == "42" since javascript is a dynamicly types language.

2021-07-21 13:53 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    } else if (action == 'code') {
Sure, I find this a good case for switch case.

2021-07-21 13:56 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    return contextLib.runAsAdmin(function () {
I don't mind writing `function () {}` instead of `() =>` when the build time is 2-3 sec 😄

2021-07-21 13:57 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +        idProviderConfig.emailCode == undefined
Yeah, good catch. the string would be equall to the keyword. 
I'll change it

2021-07-21 13:58 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +            user: user,
Our es5+ nashhorn does support it. 
I'll change it 😉

2021-07-21 14:00 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +            authLib.logout(); // this is super hacky
Yeah, can we add a authenticate or isValidLogin or simular? 
We don't have a good way of checking user + password without logging in a user.
I'm trying to make my own java class that handles this for now.

2021-07-21 14:03 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    else {
You mean we could logically remove the else? Okay, sure. 
Can we keep it? Or want me to reformat to a single return statement?

2021-07-21 14:04 UTC, poi33 commented on src/main/resources/lib/mail.js
> +    const result = mailLib.send({
Yeah i used the result a lot in debugging. I'll remove it.

2021-07-21 14:07 UTC, poi33 commented on src/main/resources/lib/render/render.js
> +        codeUrl,
We do since xp7. I try use it, but i forgot from time to time.

2021-07-21 14:14 UTC, poi33 commented on src/main/resources/lib/render/render.js
> +    const redirectUrl = portalLib.logoutUrl();
This was a pure copy from the old code. I might have wirtten it differently myself, but i would add a variable if the lines become: 
```
config: my.really.deep.nested.object.that.needs.to.have.a.variable
```

Its quite common to define your variables used inside the rest of the function on top of your code block.

2021-07-21 14:17 UTC, poi33 commented on src/main/resources/lib/render/render.js
> +    const stylePath = "themes/" + theme.split('-', 1)[0] + "-theme.css";
We do support string literals, but I did not touch this function except the variable keyword. 
Do you think we need to use string litterals here?

2021-07-21 14:27 UTC, poi33 commented on src/main/resources/lib/twoStepToken.js
> +                p.twoStepTimestamp = Date.now();
I have not gotten any issues with the number timestamp? Is it difficult to understand?

2021-07-21 14:29 UTC, poi33 commented on src/main/resources/lib/twoStepToken.js
> +    var bean = __.newBean(
I followed the way they did it in this project. Would love to know if one is better/prefered.

2021-07-22 08:40 UTC, poi33 commented on src/main/resources/assets/js/send-code.js
> +    enableFormSubmit(false);
It is hacky. Should we change something about it?

2021-07-22 12:37 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    let codeRedirect;
I try to avoid multiline ternaries. I see a lot new JS write them is it old fashioned to write if else now?

2021-07-22 12:37 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +    return contextLib.runAsAdmin(function () {
Na, I don't mind writing `function () {}` and have 2-3 sec buildtime 😄

2021-07-22 12:39 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +            user: user,
We do, i just tend to forget it. I don't have a preference, usually use the shorter one.

2021-07-22 12:47 UTC, poi33 commented on src/main/resources/idprovider/idprovider.js
> +            authLib.logout(); // this is super hacky
Until we have a proper auth lib extention (🙏) to do this, i made my own java class to check it.

2021-07-22 12:53 UTC, poi33 commented on src/main/resources/lib/render/render.js
> +        codeUrl,
It is supported, i just don't always use it. No preference between the two. I use the shorthand a bit more i think.

2021-07-22 12:58 UTC, poi33 commented on src/main/resources/lib/render/render.js
> +    const stylePath = "themes/" + theme.split('-', 1)[0] + "-theme.css";
We do support string litterals. This code was just pure copy. Did not want to mess with old code without a reason.

2021-07-22 13:01 UTC, poi33 commented on src/main/resources/lib/resetToken.js
> +    const bean = __.newBean('com.enonic.app.simpleidprovider.TokenGeneratorService');
Our xp js libs all have the bean defined inside function scope. So i guess that is best practice?

2021-07-25 16:44 UTC, rymsha commented on src/main/resources/lib/resetToken.js
> +    const bean = __.newBean('com.enonic.app.simpleidprovider.TokenGeneratorService');
newBean can be called in every function call, or in "global" space. Depends on what developer wants from that bean.

2021-07-25 16:44 UTC, rymsha commented on build.gradle
> +    include "com.enonic.lib:lib-idproviderdisplay:2.1.1-SNAPSHOT"
maybe 2.1.0 ?

2021-07-25 16:44 UTC, rymsha commented on src/main/java/com/enonic/app/simpleidprovider/AuthenticateHandler.java
> +public final class AuthenticateHandler
File an issue in XP to support that out of the box

2021-07-30 09:08 UTC, poi33 commented on build.gradle
> +    include "com.enonic.lib:lib-idproviderdisplay:2.1.1-SNAPSHOT"
2.1.1 is not released yet, so i publish to maven localy and use a snapshot version

2021-07-30 09:18 UTC, rymsha commented on build.gradle
> +    include "com.enonic.lib:lib-idproviderdisplay:2.1.1-SNAPSHOT"
But there I see no code changes between 2.1.0 and 2.1.1 snapshot...

2021-07-30 10:16 UTC, poi33 commented on build.gradle
> +    include "com.enonic.lib:lib-idproviderdisplay:2.1.1-SNAPSHOT"
It was on a local branch, created the pull request now.

2021-07-30 10:20 UTC, poi33 commented on src/main/java/com/enonic/app/simpleidprovider/AuthenticateHandler.java
> +public final class AuthenticateHandler
https://github.com/enonic/xp/issues/8987

2021-08-09 10:41 UTC, merged